### ISSUE TITLE
존재하지 않는 PUID로 프로젝트 삭제 시도 시 정상으로 삭제됐다는 문장이 출력되는 이슈

### ISSUE THREAD

**Issue by kimch0612** [CodeCraft-NSU/Database#18]
## Summary
- 존재하지 않는 PUID 혹은 이미 삭제한 PUID로 프로젝트 삭제를 시도하면 오류가 발생하지 않고 정상적으로 삭제됐다는 문장이 출력됨

## Description
- 본래 삭제 결과값이 True인 경우에만 Project deleted successfully 문장이 출력되어야 하는데, 어떠한 경우에도 모두 True로 처리됨

![image](https://github.com/user-attachments/assets/9eee63bc-4303-4562-bd25-0db3ae394a4d)

**Comment by lshbluesky** [comment]
SQL의 특성 상 DELETE 문의 WHERE 조건을 만족하는 행이 없어도 오류가 발생하지는 않으며, 단지 삭제하는 행이 없게 됩니다.
해당 버그에 대하여 수정한 소스 코드를 커밋하였습니다.
https://github.com/lshbluesky/Database/commit/39cee484e919abe436916cc69fcf6b7384aba17c

`p_no` 컬럼을 모두 조회하고 매개 변수로 받은 `pid` 값을 하나씩 차례대로 비교하는 방법보다는
COUNT 함수를 사용하는 방법이 조금 더 처리 속도가 빠르고 간단할 것 같아서 이 방법으로 수정하였습니다. :)

**Comment by lshbluesky** [comment]
처음에는 18, 19번의 이슈를 하나의 브랜치에서 모두 수정하고 PR을 생성할 예정이었지만,
다시 별도의 브랜치로 분리해서 작업하는 것이 좋을 것 같아서 18번 이슈를 해결한 PR을 먼저 생성하였습니다. #20
