### ISSUE TITLE
DB 산출물 파트에 참여자 정보 테이블 정의 필요

### ISSUE THREAD

**Issue by kimch0612** [CodeCraft-NSU/Database#27]
## Summary
- DB의 산출물 파트에 참여자 정보가 들어갈 테이블이 필요합니다.

## Description
- 산출물 파트에서 참여 인원에 대한 정보를 기입해야 하는데, 해당 정보를 저장/조회할 테이블이 존재하지 않습니다.
- 아래는 예시로 회의록 파트인데, 하단에 참석자 파트에 넣을 데이터가 존재하지 않습니다.
- 프론트엔드에서 산출물을 작성할 때, 참여 인원(참석자)을 api_project_check_user 함수를 이용해 불러와서 리스트에 띄우고, 체크박스 등을 이용해 사람을 선택하면 해당 인원의 학번이 DB에 남는 방식으로 하면 좋을 것 같습니다.
  - 다만, 프로젝트 유저가 몇명이 될지 알 수 없으므로, 학번을 특정 기호로 묶어 남긴 뒤에 이후 그 특정 기호를 이용해 다시 split하면 되지 않을까 생각합니다.
  - e.g. 20101111과 20102222, 20103333이 참여했다고 하면, 20101111;20102222;20103333 처럼 ;로 구분을 하고, 이후 다시 활용할 때는 백엔드에서 ;로 split해 활용

```python3
class MeetingMinutesPayload(BaseModel):
    """회의록 모델"""
    main_agenda: str # 안건
    date_time: str # 일시
    location: str # 장소
    participants: str # 참석인원
    responsible_person: str # 책임자명
    meeting_content: str # 회의 내용
    meeting_outcome: str # 회의 결과
    # univ_id: str <- 새로 추가; 프론트에서 문자열로 가공 후 백엔드에 제공
    pid: int = None
    doc_m_no: int = None
```

![회의록_1](https://github.com/user-attachments/assets/949796a3-e004-4ef1-a6fe-9943ecf6359d)

**Comment by lshbluesky** [comment]
내용 확인하였습니다. ✅

1. 그러면, "DB의 산출물 파트에 참여자 정보가 들어갈 테이블이 필요합니다." 에서 테이블이 아니라, 컬럼이 필요하다고 하는 것이 적합할 것 같은데, 혹시 맞을까요?

2. ERD 에서 회의록 테이블을 보면 doc_m_member 컬럼이 있으며, 이 컬럼이 참석자 정보를 저장하는 컬럼입니다. 참여 인원수를 저장하는 컬럼이 아니며, 그래서 데이터 타입도 INT 가 아닌 TEXT(문자열) 타입입니다.

3. 추가로, 프로젝트 개요서 테이블의 경우에는 프로젝트 참여자 정보를 doc_s_team 컬럼에 문자열로 저장합니다.

**Comment by kimch0612** [comment]
컬럼이 맞습니다.
안 그래도 doc_m_member가 인원 수를 기입하는건지, 아니면 사람 정보(학번 등)가 들어가는건지 좀 헷갈렸는데, 그 방향대로 가는게 맞겠네요.
그럼 doc_m_member에 위에 계획한 대로 ;를 구분자로 학번을 넣고, 불러올 때 활용하겠습니다.
추가로, 회의록 양식에서 '참석인원'파트는 doc_m_member에 있는 정보를 ;로 split하고 나온 요소의 개수를 카운트해서 기입하는 것으로 하겠습니다.
